### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by FezVrasta** [tymphillips/brackets-folders-first#1]
this is a built-in feature of brackets, u don't need an extension

**Comment by jvson** [comment]
This adds nothing.

**Comment by Carstairs** [comment]
On Mac, the folders are **not** first.  This is a great extension for Mac users - thank you!

**Comment by FezVrasta** [comment]
You can decide the behavior using the built-in options of Brackets. No need for an extension.

**Comment by tymphillips** [comment]
When I created this, Brackets didn't have this option. It does now
